#!/bin/bash

# Script to count the number of myths and generate LaTeX macro
# Usage: ./count-myths.sh

TEX_FILE="mythen.tex"
OUTPUT_FILE="myth-count.tex"

if [ ! -f "$TEX_FILE" ]; then
    echo "Error: $TEX_FILE not found"
    exit 1
fi

# Count occurrences of \mythslide, excluding the macro definition
COUNT=$(grep '\\mythslide' "$TEX_FILE" | grep -v '\\newcommand' | wc -l)

echo "Found $COUNT myths"

# Generate LaTeX macro file
cat > "$OUTPUT_FILE" << EOF
% Auto-generated file - DO NOT EDIT MANUALLY
% Generated by count-myths.sh on $(date)
\\newcommand{\\totalmythen}{$COUNT}
EOF

echo "Generated $OUTPUT_FILE with count: $COUNT"
