#!/bin/bash

# Script to count the number of misconceptions and generate LaTeX macro
# Usage: ./count-misconceptions.sh

TEX_FILE="2025-missverstaendnisse.tex"
OUTPUT_FILE="misconception-count.tex"

if [ ! -f "$TEX_FILE" ]; then
    echo "Error: $TEX_FILE not found"
    exit 1
fi

# Count occurrences of \misconceptionslide, excluding the macro definition
COUNT=$(grep '\\misconceptionslide' "$TEX_FILE" | grep -v '\\newcommand' | wc -l)

echo "Found $COUNT misconceptions"

# Generate LaTeX macro file
cat > "$OUTPUT_FILE" << EOF
% Auto-generated file - DO NOT EDIT MANUALLY
% Generated by count-misconceptions.sh on $(date)
\\newcommand{\\totalmisconceptions}{$COUNT}
EOF

echo "Generated $OUTPUT_FILE with count: $COUNT"